package libs

const (
	AUTH_LOGIN_UNSUCCESS               = "Đăng nhập không thành công"
	AUTH_SUCCESS                       = "Ủy quyền thành công"
	AUTH_UNSUCCESS_TOKEN_EXPIRED       = "Token đăng nhập hết thời hạn sử dụng"
	AUTH_UNSUCCESS_NO_TOKEN            = "Ủy quyền không thành công, không tìm thấy token"
	AUTH_UNSUCCESS_INVALID_TOKEN       = "Ủy quyền không thành công, token không hợp lệ"
	AUTH_UNSUCCESS_NO_CLAIMS           = "Ủy quyền không thành công, token không tồn tại"
	AUTH_UNSUCCESS_NO_INFORMATION      = "Thông tin xác thực không tồn tại"
	AUTH_UNSUCCESS_INFORMATION_INVALID = "Thông tin xác thực không chính xác"
	AUTH_UNSUCCESS_CANT_GENERATE_TOKEN = "Tạo token không thành công"
	AUTH_LOGIN_SUCCESS                 = "Đăng nhập thành công"
	AUTH_LOGOUT_SUCCESS                = "Đăng xuất thành công"
	SEND_IMAGE_SUCCESS                 = "Gửi ảnh thành công"
	SEND_IMAGE_UNSUCCESS               = "Gửi ảnh không thành công"
	DELETE_IMAGE_SUCCESS               = "Xóa ảnh thành công"
	DELETE_IMAGE_UNSUCCESS             = "Xóa ảnh không thành công"
	SERVER_ERROR                       = "Lỗi server"
	INPUT_ERROR                        = "Lỗi dữ liệu nhập vào"
	CANT_FIND_IMAGE_ERROR              = "Lỗi không tìm thấy hình ảnh"
	GET_LIMIT_UNSUCCESS                = "Lấy giới hạn không thành công"
	GET_PAGE_UNSUCCESS                 = "Lấy trang không thành công"
	CREATE_SUCCESS                     = "Nhập dữ liệu thành công"
	CREATE_UNSUCCESS                   = "Nhập dữ liệu không thành công"
	UPDATE_SUCCESS                     = "Sửa dữ liệu thành công"
	UPDATE_UNSUCCESS                   = "Cập nhập dữ liệu không thành công"
	REMOVE_SUCCESS                     = "Xóa dữ liệu thành công"
	REMOVE_UNSUCCESS                   = "Xóa dữ liệu không thành công"
	GET_DATA_UNSUCCESS                 = "Lấy dữ liệu không thành công"
)
