INSERT INTO blogcategory (name) VALUES ('category 1');
INSERT INTO blogcategory (name) VALUES ('category 2');
INSERT INTO blogcategory (name) VALUES ('category 3');
INSERT INTO blogcategory (name) VALUES ('category 4');
INSERT INTO blogcategory (name) VALUES ('category 5');
INSERT INTO blogcategory (name) VALUES ('category 6');
INSERT INTO blogcategory (name) VALUES ('category 7');
INSERT INTO blogcategory (name) VALUES ('category 8');
INSERT INTO blogcategory (name) VALUES ('category 9');
INSERT INTO blogcategory (name) VALUES ('category 10');
INSERT INTO blogcategory (name) VALUES ('category 11');
INSERT INTO blogcategory (name) VALUES ('category 12');
INSERT INTO blogcategory (name) VALUES ('category 13');
INSERT INTO blogcategory (name) VALUES ('category 14');
INSERT INTO blogcategory (name) VALUES ('category 15');
INSERT INTO blogcategory (name) VALUES ('category 16');
INSERT INTO blogcategory (name) VALUES ('category 17');
INSERT INTO blogcategory (name) VALUES ('category 18');
INSERT INTO blogcategory (name) VALUES ('category 19');
INSERT INTO blogcategory (name) VALUES ('category 20');
INSERT INTO blogcategory (name) VALUES ('category 21');
INSERT INTO blogcategory (name) VALUES ('category 22');
INSERT INTO blogcategory (name) VALUES ('category 23');
INSERT INTO blogcategory (name) VALUES ('category 24');
INSERT INTO blogcategory (name) VALUES ('category 25');
INSERT INTO blogcategory (name) VALUES ('category 26');
INSERT INTO blogcategory (name) VALUES ('category 27');
INSERT INTO blogcategory (name) VALUES ('category 28');
INSERT INTO blogcategory (name) VALUES ('category 29');
INSERT INTO blogcategory (name) VALUES ('category 30');
INSERT INTO blogcategory (name) VALUES ('category 31');
INSERT INTO blogcategory (name) VALUES ('category 32');
INSERT INTO blogcategory (name) VALUES ('category 33');
INSERT INTO blogcategory (name) VALUES ('category 34');
INSERT INTO blogcategory (name) VALUES ('category 35');
INSERT INTO blogcategory (name) VALUES ('category 36');
INSERT INTO blogcategory (name) VALUES ('category 37');
INSERT INTO blogcategory (name) VALUES ('category 38');
INSERT INTO blogcategory (name) VALUES ('category 39');
INSERT INTO blogcategory (name) VALUES ('category 40');
INSERT INTO blogcategory (name) VALUES ('category 41');
INSERT INTO blogcategory (name) VALUES ('category 42');
INSERT INTO blogcategory (name) VALUES ('category 43');
INSERT INTO blogcategory (name) VALUES ('category 44');
INSERT INTO blogcategory (name) VALUES ('category 45');
INSERT INTO blogcategory (name) VALUES ('category 46');
INSERT INTO blogcategory (name) VALUES ('category 47');
INSERT INTO blogcategory (name) VALUES ('category 48');
INSERT INTO blogcategory (name) VALUES ('category 49');
INSERT INTO blogcategory (name) VALUES ('category 50');
INSERT INTO blogcategory (name) VALUES ('category 51');
INSERT INTO blogcategory (name) VALUES ('category 52');
INSERT INTO blogcategory (name) VALUES ('category 53');
INSERT INTO blogcategory (name) VALUES ('category 54');
INSERT INTO blogcategory (name) VALUES ('category 55');
INSERT INTO blogcategory (name) VALUES ('category 56');
INSERT INTO blogcategory (name) VALUES ('category 57');
INSERT INTO blogcategory (name) VALUES ('category 58');
INSERT INTO blogcategory (name) VALUES ('category 59');
INSERT INTO blogcategory (name) VALUES ('category 60');

INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 1');
INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 2');
INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 3');
INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 4');
INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 5');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 6');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 7');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 8');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 9');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 10');
INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 11');
INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 12');
INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 13');
INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 14');
INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 15');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 16');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 17');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 18');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 19');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 20');
INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 21');
INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 22');
INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 23');
INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 24');
INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 25');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 26');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 27');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 28');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 29');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 30');
INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 31');
INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 32');
INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 33');
INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 34');
INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 35');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 36');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 37');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 38');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 39');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 40');
INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 41');
INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 42');
INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 43');
INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 44');
INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 45');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 46');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 47');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 48');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 49');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 50');
INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 51');
INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 52');
INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 53');
INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 54');
INSERT INTO blogtag (blogcategory_id, name) VALUES (1, 'tag 55');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 56');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 57');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 58');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 59');
INSERT INTO blogtag (blogcategory_id, name) VALUES (2, 'tag 60');

INSERT INTO blogfile (filename) VALUES ('filename-1.md');
INSERT INTO blogfile (filename) VALUES ('filename-2.md');
INSERT INTO blogfile (filename) VALUES ('filename-3.md');
INSERT INTO blogfile (filename) VALUES ('filename-4.md');
INSERT INTO blogfile (filename) VALUES ('filename-5.md');
INSERT INTO blogfile (filename) VALUES ('filename-6.md');
INSERT INTO blogfile (filename) VALUES ('filename-7.md');
INSERT INTO blogfile (filename) VALUES ('filename-8.md');
INSERT INTO blogfile (filename) VALUES ('filename-9.md');
INSERT INTO blogfile (filename) VALUES ('filename-10.md');
INSERT INTO blogfile (filename) VALUES ('filename-11.md');
INSERT INTO blogfile (filename) VALUES ('filename-12.md');
INSERT INTO blogfile (filename) VALUES ('filename-13.md');
INSERT INTO blogfile (filename) VALUES ('filename-14.md');
INSERT INTO blogfile (filename) VALUES ('filename-15.md');
INSERT INTO blogfile (filename) VALUES ('filename-16.md');
INSERT INTO blogfile (filename) VALUES ('filename-17.md');
INSERT INTO blogfile (filename) VALUES ('filename-18.md');
INSERT INTO blogfile (filename) VALUES ('filename-19.md');
INSERT INTO blogfile (filename) VALUES ('filename-20.md');
INSERT INTO blogfile (filename) VALUES ('filename-21.md');
INSERT INTO blogfile (filename) VALUES ('filename-22.md');
INSERT INTO blogfile (filename) VALUES ('filename-23.md');
INSERT INTO blogfile (filename) VALUES ('filename-24.md');
INSERT INTO blogfile (filename) VALUES ('filename-25.md');
INSERT INTO blogfile (filename) VALUES ('filename-26.md');
INSERT INTO blogfile (filename) VALUES ('filename-27.md');
INSERT INTO blogfile (filename) VALUES ('filename-28.md');
INSERT INTO blogfile (filename) VALUES ('filename-29.md');
INSERT INTO blogfile (filename) VALUES ('filename-30.md');
INSERT INTO blogfile (filename) VALUES ('filename-31.md');
INSERT INTO blogfile (filename) VALUES ('filename-32.md');
INSERT INTO blogfile (filename) VALUES ('filename-33.md');
INSERT INTO blogfile (filename) VALUES ('filename-34.md');
INSERT INTO blogfile (filename) VALUES ('filename-35.md');
INSERT INTO blogfile (filename) VALUES ('filename-36.md');
INSERT INTO blogfile (filename) VALUES ('filename-37.md');
INSERT INTO blogfile (filename) VALUES ('filename-38.md');
INSERT INTO blogfile (filename) VALUES ('filename-39.md');
INSERT INTO blogfile (filename) VALUES ('filename-40.md');
INSERT INTO blogfile (filename) VALUES ('filename-41.md');
INSERT INTO blogfile (filename) VALUES ('filename-42.md');
INSERT INTO blogfile (filename) VALUES ('filename-43.md');
INSERT INTO blogfile (filename) VALUES ('filename-44.md');
INSERT INTO blogfile (filename) VALUES ('filename-45.md');
INSERT INTO blogfile (filename) VALUES ('filename-46.md');
INSERT INTO blogfile (filename) VALUES ('filename-47.md');
INSERT INTO blogfile (filename) VALUES ('filename-48.md');
INSERT INTO blogfile (filename) VALUES ('filename-49.md');
INSERT INTO blogfile (filename) VALUES ('filename-50.md');
INSERT INTO blogfile (filename) VALUES ('filename-51.md');
INSERT INTO blogfile (filename) VALUES ('filename-52.md');
INSERT INTO blogfile (filename) VALUES ('filename-53.md');
INSERT INTO blogfile (filename) VALUES ('filename-54.md');
INSERT INTO blogfile (filename) VALUES ('filename-55.md');
INSERT INTO blogfile (filename) VALUES ('filename-56.md');
INSERT INTO blogfile (filename) VALUES ('filename-57.md');
INSERT INTO blogfile (filename) VALUES ('filename-58.md');
INSERT INTO blogfile (filename) VALUES ('filename-59.md');
INSERT INTO blogfile (filename) VALUES ('filename-60.md');

INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (1, 1);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (2, 1);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (3, 1);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (4, 1);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (5, 1);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (6, 1);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (7, 1);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (8, 1);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (9, 1);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (10, 1);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (1, 2);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (2, 2);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (3, 2);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (4, 2);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (5, 2);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (6, 2);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (7, 2);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (8, 2);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (9, 2);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (10, 2);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (1, 3);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (2, 3);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (3, 3);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (4, 3);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (5, 3);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (6, 3);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (7, 3);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (8, 3);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (9, 3);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (10, 3);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (1, 4);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (2, 4);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (3, 4);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (4, 4);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (5, 4);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (6, 4);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (7, 4);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (8, 4);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (9, 4);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (10, 4);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (1, 5);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (2, 5);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (3, 5);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (4, 5);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (5, 5);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (6, 5);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (7, 5);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (8, 5);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (9, 5);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (10, 5);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (1, 6);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (2, 6);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (3, 6);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (4, 6);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (5, 6);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (6, 6);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (7, 6);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (8, 6);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (9, 6);
INSERT INTO blogtagfile (blogtag_id, blogfile_id) VALUES (10, 6);
