name: Github Actions
run-name: ${{ github.actor }} is running Github Actions 🚀
on:
  push:
    branches:
      - '*'

jobs:
  build-test-push:
    name: Build dev docker image
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Setup Docker, Docker compose and build start
      uses: hoverkraft-tech/compose-action@v2.0.1

    - name: Generate database documentation
      run: sh script.sh generate-database-doc
      if: always()

    - name: Test api service auth
      run: sh script.sh test-api-service-auth
      if: always()

    - name: Test api service blogcategory
      run: sh script.sh test-api-service-blogcategory
      if: always()

    - name: Test api service blogtag
      run: sh script.sh test-api-service-blogtag
      if: always()

    - name: Test api service blogfile
      run: sh script.sh test-api-service-blogfile
      if: always()

    - name: Test api service blogtagfile
      run: sh script.sh test-api-service-blogtagfile
      if: always()

    # - name: Test api controller auth
    #   run: sh script.sh test-api-controller-auth
    #   if: always()

#    - name: Login to Gitea Container Registry
#      uses: docker/login-action@v3
#      with:
#        registry: git.planetv.io.vn
#        username: ${{ gitea.actor }}
#        password: ${{ secrets.RW_PACKAGES }}

#    - name: Tag and push docker image
#      run: |
#        docker tag planetv-web-app-image:latest git.planetv.io.vn/planetv/planetv-web-app/planetv-web-app:latest
#        docker push git.planetv.io.vn/planetv/planetv-web-app/planetv-web-app:latest

    - name: Remove all container and image
      run: sh script.sh remove-all
      if: always()

  nix-devshell:
    name: Test nix flake devshell
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Setup nix
      uses: cachix/install-nix-action@v27

    - name: Enter nix flake devshell
      run: nix develop .
      if: always()
